version: '3.5'
services:
  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - '1883:1883'