name: build
on: push
jobs:
  Test_Build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v2
      - name: Install PlatformIO
        run: pip install -U platformio
      - name: Create Dummy secrets.h file
        run: touch include/secrets.h && echo "#define SECRET_SSID "testSSID"" >> include/secrets.h && echo "#define SECRET_PASS "fakepass"" >> include/secrets.h
      - name: Test build
        run: pio run -e esp12e